version: '3'
services:
  backend:
    image: ghazi11/back
    ports:
      - "8082:8080"  # Map port 8081 on the host to port 8080 on the container
    build: .
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  frontend:
    image: ghazi11/frant
    ports:
      - "80:80"  # Map port 80 on the host to port 80 on the container

  mysql:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3333:3306"  # Map port 3333 on the host to port 3306 on the container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    volumes:
      - /home/ghazi/Desktop/DB:/var/lib/mysql
    restart: unless-stopped