

version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"  # Map host port 3306 to container port 3306
    environment:
      MYSQL_DATABASE: mysql
    volumes:
      - ./home/ghazi/Desktop/DB:/docker-entrypoint-initdb.d/data.sql
    networks:
      - docker-network

  spring:
    image: ghazi11/back1
    container_name: test3_backend_1
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mysql?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql
    networks:
      - docker-network
    volumes:
      - ./home/ghazi/Desktop/DB:/app/data

  angular:
    image: ghazi11/frantend
    container_name: test3_frantend_1
    ports:
      - "80:80"
    depends_on:
      - spring
    networks:
      - docker-network
    volumes:
      - ./home/ghazi/Desktop/DB:/app/dist

networks:
  docker-network:





