version: '3'
services:
  backend:
    image: ghazi11/back
    ports:
      - "8081:8080"  # Map port 8081 on the host to port 8080 on the container
    restart: always
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3333/devops?createDatabaseIfNotExist=true  # Update port to 3333
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    image: ghazi11/frant
    ports:
      - "80:80"  # Map port 80 on the host to port 80 on the container

  mysql:
    image: mysql:latest
    ports:
      - "3333:3306"  # Map port 3333 on the host to port 3306 on the container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    volumes:
      - /home/ghazi/Desktop/DB:/var/lib/mysql
    restart: unless-stopped